### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by LowlandwasTaken** [anastazialol/Discord-Bot-Website#1] opened 2023-02-24 18:08 UTC
Hello i cant seem to find a way to contact u!

**Comment by anastazialol** [comment] 2023-02-25 13:05
Hello, why would you like to contact me?

**Comment by LowlandwasTaken** [comment] 2023-02-28 06:46
I have some problem regarding that site. I saw ur discord but ur messages are locked so i contacted u here!

**Comment by LowlandwasTaken** [comment] 2023-02-28 08:15
U may look into my [website](https://whispervc.xyz/) it has some slight problems.

**Comment by anastazialol** [comment] 2023-02-28 09:20
Will look into it, thank you.

**Comment by anastazialol** [comment] 2023-02-28 16:42
Hello if the issue was with the images and the buttons the problem is now fixed. Will publish the new changes within 10 minutes.

**Closed by anastazialol** 2023-02-28 16:42 UTC
Labels: bug

**Comment by LowlandwasTaken** [comment] 2023-03-01 12:42
IDK if im dumb but the image is still not fixed.
